spring:
    datasource:
        url: jdbc:mysql://localhost:3306/java?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
        username: java
        password: java
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8081
app:
  auth:
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080
