# TODO: rename this file in "application-secret.yml"
spring:
    security:
      oauth2:
        client:
          registration:
            google:
              clientId: {YOUR ID}
              clientSecret: {YOUR KEY}

app:
  auth:
    tokenSecret: {YOUR TOKEN}
